[package]
name = "rate_limiter"
version = "0.1.0"
authors = ["Vedran Vucetic <vedran.vucetic@gmail.com>"]
edition = "2018"
readme = "README.md"
include = ["README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
